### ISSUE TITLE
Path munging is OS-dependent

### ISSUE THREAD

**Issue by bkuczenski** [AntelopeLCA/core#5]
`StaticCatalog._localize_source()` and `StaticCatalog.abs_path()` fail on Windows because paths are stored with double-backslashes.

**Comment by bkuczenski** [comment]
here is the problem.
 - `antelope_core.catalog.catalog.StaticCatalog._localize_source(path)`
 - `antelope_core.catalog.catalog.StaticCatalog.abs_path(path)`

The objective is to determine when a path is relative to the catalog root, and if so, remove and replace that with `$CATALOG_ROOT` -- this way config files containing the path will not depend on the location of the catalog.

The problem is that it does this with regex. Windows paths (all paths derived with `os.path` operations) represented as strings contain a double-backslash, which is somehow converted to a single backslash BEFORE going into the regex, raising a "bad escape sequence" error.

To reproduce: 
 - install antelope_core on a windows machine.
 - specify using export ANTELOPE_CATALOG_ROOT="C:\path\to\catalog", preferably so the path contains an unrecognized escape sequence, such as `\\Python`
 - attempt to run the unit tests. The problem should occur when running antelope_catalog.data_sources.tests.test_uslci.py in test_10_index(), when it attempts to create an index file

Note that even if the regex error is not encountered, the created path will probably be broken.  Also, there is no telling what other os-dependent problems might be encountered, since we do not test for them.

**Comment by bkeane** [comment]
https://www.geeksforgeeks.org/python-os-path-normpath-method/
